---
name: Publish Docker image
on:
    push:
        tags:
            - 'v*'

jobs:
    push-to-registry:
        runs-on: ubuntu-latest
        steps:
        -
            name: 'Checkout GitHub Action'
            uses: actions/checkout@main
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
        -
            name: 'Login to DockerHub'
            if: github.event_name != 'pull_request'
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -
          name: 'Build and push'
          uses: docker/build-push-action@v2
          with:
            context: .
            push: ${{ github.event_name != 'pull_request' }}
            tags: pwnz0r/node:${{ github.sha }}